//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPerritosWCF.DogServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DogServiceReference.IDogService")]
    public interface IDogService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDogService/ObtenerImagenAleatoriaPerro", ReplyAction="http://tempuri.org/IDogService/ObtenerImagenAleatoriaPerroResponse")]
        string ObtenerImagenAleatoriaPerro();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDogService/ObtenerImagenAleatoriaPerro", ReplyAction="http://tempuri.org/IDogService/ObtenerImagenAleatoriaPerroResponse")]
        System.Threading.Tasks.Task<string> ObtenerImagenAleatoriaPerroAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDogServiceChannel : ProyectoPerritosWCF.DogServiceReference.IDogService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DogServiceClient : System.ServiceModel.ClientBase<ProyectoPerritosWCF.DogServiceReference.IDogService>, ProyectoPerritosWCF.DogServiceReference.IDogService {
        
        public DogServiceClient() {
        }
        
        public DogServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DogServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DogServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DogServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ObtenerImagenAleatoriaPerro() {
            return base.Channel.ObtenerImagenAleatoriaPerro();
        }
        
        public System.Threading.Tasks.Task<string> ObtenerImagenAleatoriaPerroAsync() {
            return base.Channel.ObtenerImagenAleatoriaPerroAsync();
        }
    }
}
